### ISSUE TITLE
Make ray an optional dependency

### ISSUE THREAD

**Issue by hakonanes** [USNavalResearchLaboratory/PyEBSDIndex#25]
I suggest to make `ray` an optional dependency, since it is only used in the package in one file for a quite specific purpose (distributed indexing):
- `index_pats_distributed()` (https://github.com/USNavalResearchLaboratory/PyEBSDIndex/blob/main/pyebsdindex/ebsd_index.py#L114)
- `IndexerRay` (https://github.com/USNavalResearchLaboratory/PyEBSDIndex/blob/main/pyebsdindex/ebsd_index.py#L432)

Another argument against having `ray[default]` as a dependency is that it is not generally available. E.g. it is not available from Anaconda for macOS (as mentioned in #17) or for Python 3.10 from Anaconda.

I haven't used the above mentioned function and class and there aren't any tests using them, so I'm reluctant to make a PR where they are moved but work when `ray` is installed.

**Comment by drowenhorst-nrl** [comment]
Hmmm - this is tough.  I should have probably just named it index_pats_multipro or something, since I have not actually run this on a distributed cluster, I and a few others around my lab use this a lot for indexing full datasets.  I think Ray is growing in popularity, and it had some key features that Dask and multiprocessing did not.  

But I also see that Ray from PyPI (ironically) is not yet working on Windows & Python 3.10.  At least from what I can see, the Ray project tends to be *INX first, Windows eventually.  

 https://github.com/conda-forge/ray-packages-feedstock/issues/2
Indicates that the MacOS of the conda-forge distro is coming soon?  The whole "you don't need to be the developer to post stuff to conda-forge" is all a bit strange to me.  

So it is clear that Ray, being in active development and growing, but not yet pervasive is an issue.  To accomplish making Ray optional, I guess  multiprocess indexing would have to move into its own file/module?

**Comment by hakonanes** [comment]
> since I have not actually run this on a distributed cluster

I did not this, then I'll start using that instead of the single threaded `index_pats()`!

> So it is clear that Ray, being in active development and growing, but not yet pervasive is an issue

I'd very much like for kikuchipy to streamline use of Hough indexing and NLPAR from our `EBSD` class (and all the IO plugins) by adding PyEBSDIndex as a dependency. But that's not possible until PyEBSDIndex is available via pip and conda-forge for all three platforms on Python >= 3.8 (we also support 3.7) including 3.10 (which we test against).

> To accomplish making Ray optional, I guess multiprocess indexing would have to move into its own file/module?

Yes, I think something like that should work. Ideally, one should only check whether `ray` is available in one place, and then reuse that boolean variable everywhere `ray` is attempted to be used.

If this is not something you'd like to work on or have time for, I might find time to do it next week.

**Comment by hakonanes** [comment]
> https://github.com/conda-forge/ray-packages-feedstock/issues/2 Indicates that the MacOS of the conda-forge distro is coming soon?

Perhaps, the latest commits in that direction was done 10 months ago here: https://github.com/conda-forge/ray-packages-feedstock/pull/21.

> The whole "you don't need to be the developer to post stuff to conda-forge" is all a bit strange to me.

I agree to some extent. Apparently it is not required at all as mentioned in [their docs](https://conda-forge.org/docs/maintainer/maintainer_faq.html#mfaq-package-submit). I would guess this policy makes more packages downloadable via Anaconda since people who aren't package developers but know how to set up conda-forge builds can upload packages.

**Comment by hakonanes** [comment]
This was done in #29.
